apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  containers:
  - command:
    - sleep
    - "100"
    image: busybox
    name: busybox-pod
    resources: {}
  restartPolicy: Never
  nodeSelector:
          role: worker2

